#define IDM_EXIT           100
#define IDM_ABOUT          101
#define IDM_TEST           200

LRESULT CALLBACK WndProc  (HWND, UINT, WPARAM, LPARAM);
LRESULT CALLBACK About    (HWND, UINT, WPARAM, LPARAM);
