#define IDM_EXIT           100
#define IDM_TEST           200
#define IDM_ABOUT          301

#define IDC_CHECKBOX       101
#define IDC_RADIO1         102
#define IDC_RADIO2         103

LRESULT CALLBACK WndProc  (HWND, UINT, WPARAM, LPARAM);
LRESULT CALLBACK About    (HWND, UINT, WPARAM, LPARAM);
LRESULT CALLBACK TestDlgProc(HWND, UINT, WPARAM, LPARAM);
